[build]
    command = "npm run build"  # El comando para construir tu proyecto
    publish = "."  
[[redirects]]
  from = "/fetch/*"
  to = "/.netlify/functions/proxy?url=:splat"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"